Fixed issues with jest
Fixed issues with jest, where TypeError: dupMap.get is not a function
errors were causing test in the root project to fail. Also fixed the
compile errors in the psl-lint related test cases. A lot of those test
cases cannot easily move to the psl-lint module, because they rely on
some vscode plugin code.